# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: patchscope.proto
# Protobuf Python Version: 5.28.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    3,
    '',
    'patchscope.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10patchscope.proto\"@\n\x10PatchscopeConfig\x12\x15\n\rsource_layers\x18\x01 \x03(\x05\x12\x15\n\rtarget_layers\x18\x02 \x03(\x05\"\xed\x01\n\x10\x45valuationConfig\x12\x11\n\tmodel_key\x18\x01 \x01(\t\x12\x0f\n\x07\x64\x61taset\x18\x02 \x01(\t\x12\x15\n\rtarget_prompt\x18\x03 \x01(\t\x12;\n\x0elabel_to_token\x18\x04 \x03(\x0b\x32#.EvaluationConfig.LabelToTokenEntry\x12,\n\x11patchscope_config\x18\x05 \x01(\x0b\x32\x11.PatchscopeConfig\x1a\x33\n\x11LabelToTokenEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\x8c\x01\n\x10\x45valuationResult\x12\x17\n\x0fresult_set_name\x18\x01 \x01(\t\x12!\n\x06\x63onfig\x18\x02 \x01(\x0b\x32\x11.EvaluationConfig\x12\x10\n\x08\x61\x63\x63uracy\x18\x03 \x01(\x01\x12\x13\n\x0bnum_correct\x18\x04 \x01(\x03\x12\x15\n\rnum_evaluated\x18\x05 \x01(\x03\"7\n\x11\x45valuationResults\x12\"\n\x07results\x18\x01 \x03(\x0b\x32\x11.EvaluationResultb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'patchscope_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EVALUATIONCONFIG_LABELTOTOKENENTRY']._loaded_options = None
  _globals['_EVALUATIONCONFIG_LABELTOTOKENENTRY']._serialized_options = b'8\001'
  _globals['_PATCHSCOPECONFIG']._serialized_start=20
  _globals['_PATCHSCOPECONFIG']._serialized_end=84
  _globals['_EVALUATIONCONFIG']._serialized_start=87
  _globals['_EVALUATIONCONFIG']._serialized_end=324
  _globals['_EVALUATIONCONFIG_LABELTOTOKENENTRY']._serialized_start=273
  _globals['_EVALUATIONCONFIG_LABELTOTOKENENTRY']._serialized_end=324
  _globals['_EVALUATIONRESULT']._serialized_start=327
  _globals['_EVALUATIONRESULT']._serialized_end=467
  _globals['_EVALUATIONRESULTS']._serialized_start=469
  _globals['_EVALUATIONRESULTS']._serialized_end=524
# @@protoc_insertion_point(module_scope)
